config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :salespeople
    resources :buyers
    resources :sales
    resources :affiliates
  end
  
  devise_for :affiliates
  devise_for :admins, controllers: { sessions: 'admin/sessions'}

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  authenticated :affiliate_user do
    root to: "affiliate#index", as: :affiliate_root
  end

  # resources :affiliate

  get "admin" => "admin#index"
  get "admin/payment_history" => "admin#payment_history"
  get "affiliate" => "affiliate#index"
  get "affiliate/profile" => "affiliate#profile"
  get "affiliate/profile/edit" => "affiliate#edit"
  patch "affiliate/update" => "affiliate#update"
  get "affiliate/sale" => "affiliate#sale"
  get "affiliate/account" => "affiliate#account"
  get "affiliate/account_setting" => "affiliate#account_setting"
  get "affiliate/account_setting/edit/" => "affiliate#edit_account_setting"
  patch "affiliate/account_setting/update" => "affiliate#update_account_setting"

  get "sales/invest/form/:ref_code" => "sales#new", as: :sales_form
  post "sales/invest/form/create" => "sales#create"
  get "sales/invest/message" => "sales#message", as: :sales_message

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: redirect('affiliates/sign_in')
end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  has_one_attached :attached_id

  has_many :sales

  def ref_code
    return self.id.to_s.rjust(4, '0')
  end

  def payout
    return self.sales.any? ? self.sales.sum(:payout) : 0
  end

  def last_payment
    return self.sales.any? ? self.sales.last.updated_at.strftime("%B %d, %Y") : ''
  end
end

app/controllers/admin/affiliates_controller.rb
class Admin::AffiliatesController < AdminController
  def index
    respond_to do |format|
      format.html do
        @admin_affiliates = Affiliate.all.order(id: :asc)
      end
      format.xlsx do
        @admin_affiliates = Affiliate.all.order(id: :asc)
        render xlsx: 'admin/affiliates', template: 'admin/affiliates/template'
      end
    end
  end

  def new
    @admin_affiliate = Affiliate.new
  end

  def show
    @affiliate = Affiliate.find(params[:id])

    if @affiliate.birthday.present?
      now = Time.now.utc.to_date
      @age = now.year - @affiliate.birthday.to_date.year

      if (now.month < @affiliate.birthday.to_date.month)
        @age = @age - 1
      end
    end
  end

  def create
    @admin_affiliate = Affiliate.new(admin_affiliate_params)

    respond_to do |format|
      if @admin_affiliate.save
        format.html { redirect_to admin_affiliates_url(@admin_affiliate), notice: "Affiliate was successfully created." }
        format.json { render :show, status: :created, location: @admin_affilliate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_affilliate.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def admin_affiliate_params
    params.require(:affiliate).permit(:fullname, :email, :password, :password_confirmation, :address, :mobile)
  end
end

app/controllers/affiliate_controller.rb
class AffiliateController < ApplicationController
  layout 'affiliate'
  before_action :authenticate_affiliate!
  before_action :set_affiliate, only: %i[index profile edit update account_setting edit_account_setting update_account_setting]

  def index
    @pending = current_affiliate.sales.pending.count
    @paid = current_affiliate.sales.paid.count
  end

  def profile
    if @affiliate.birthday.present?
      now = Time.now.utc.to_date
      @age = now.year - @affiliate.birthday.to_date.year

      if (now.month < @affiliate.birthday.to_date.month)
        @age = @age - 1
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|

      if @affiliate.update(affiliate_params)
        format.html { redirect_to affiliate_profile_path, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @affiliate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @affiliate.errors, status: :unprocessable_entity }
      end
    end
  end

  def sale
    @sales = current_affiliate.sales
  end

  def account
  end

  def account_setting
  end

  def edit_account_setting
  end

  def update_account_setting
    respond_to do |format|

      if @affiliate.update(affiliate_params)
        format.html { redirect_to affiliate_account_setting_path, notice: "Account Settings was successfully updated." }
        format.json { render :show, status: :ok, location: @affiliate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @affiliate.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    def set_affiliate
      @affiliate = Affiliate.find(current_affiliate.id)
    end

    def affiliate_params
      params.require(:affiliate).permit(:birthday, :address, :mobile, :password, :password_confirmation, :fb, :ig, :tiktok, :youtube, :others, :type_of_id, :avatar, :attached_id, :bank, :account_name, :account_no)
    end
end

app/helpers/admin/affiliates_helper.rb
module Admin::AffiliatesHelper
end

app/views/admin/affiliates/index.html.erb
<h1 class="text-2xl text-green-800 text-center uppercase font-medium mt-12">Affiliate Database</h1>

<div class="text-end">
    <%= link_to 'Export to Excel', admin_affiliates_path(format: :xlsx), target: :_blank, class: 'py-2 px-4 bg-green-800 text-white rounded' %>
    <%= link_to 'Add New', new_admin_affiliate_path, class: 'py-2 px-4 bg-green-800 text-white rounded' %>
</div>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-12">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Referral Code
                </th>
                <th scope="col" class="px-6 py-3">
                    Seller Name
                </th>
                <th scope="col" class="px-6 py-3">
                    Email Address
                </th>
                <th scope="col" class="px-6 py-3">
                    Address
                </th>
                <th scope="col" class="px-6 py-3">
                    Contact No.
                </th>
            </tr>
        </thead>
        <tbody>
            <% @admin_affiliates.each do |affiliate| %>
                <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        <%= affiliate.id.to_s.rjust(4, '0') %>
                    </th>
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        <%= link_to admin_affiliate_path(affiliate), class: 'link' do %>
                            <%= affiliate.fullname %>
                        <% end %>
                    </th>
                    <td class="px-6 py-4">
                        <%= affiliate.email %>
                    </td>
                    <td class="px-6 py-4">
                        <%= affiliate.address %>
                    </td>
                    <td class="px-6 py-4">
                        <%= affiliate.mobile %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>


app/views/admin/affiliates/new.html.erb
<h1 class="text-2xl text-center uppercase font-medium mt-8 mb-4">Add New Affiliate</h1>

<div>
  <%= form_with model: [:admin, @admin_affiliate], class: 'space-y-3' do |form| %>
    <% if form.object.errors.any? %>
        <% form.object.errors.full_messages.each do |message| %>
            <div class="text-center">
                <%= message %>
            </div>
        <% end %>
    <% end %>

    <div class="grid grid-cols-4 w-8/12 ml-28 gap-2 items-center mt-10 auto-cols-min">
      <%= form.label :fullname, class: 'text-end' %>
      <%= form.text_field :fullname, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>

      <%= form.label :address, class: 'text-end' %>
      <%= form.text_field :address, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
    
      <%= form.label :mobile, class: 'text-end' %>
      <%= form.text_field :mobile, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
    
      <%= form.label :email, class: 'text-end' %>
      <%= form.email_field :email, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>

      <%= form.label :password, class: 'text-end' %>
      <%= form.password_field :password, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
      
      <div class="text-end">
        <%= form.label :password_confirmation, class: 'text-end' %>
      </div>
      <div class="col-span-3">
        <%= form.password_field :password_confirmation, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent w-full" %>
      </div>
    </div>

    <div class="actions text-center">
      <%= form.submit "Submit", class: "py-2 px-4 bg-green-800 rounded text-white" %>
    </div>
  <% end %>
</div>

app/views/admin/affiliates/show.html.erb
<div class="px-5">
    <%= image_tag @affiliate.avatar.present? ? @affiliate.avatar : 'user.png', alt: 'src', class: "w-36 h-36 inline-block rounded-full" %>
    <h1 class="inline-block text-3xl"><%= @affiliate.fullname %></h1>

    <div class="grid grid-cols-4 w-8/12 ml-28 gap-2">
        <p class="text-end">Referral Code:</p>
        <p class="border-b col-span-3"><%= @affiliate.id.to_s.rjust(4, '0') %></p>
        
        <p class="text-end">Birthday:</p>
        <p class="border-b col-span-3"><%= @affiliate.birthday.present? ? @affiliate.birthday.strftime("%B %d, %Y") : '' %></p>

        <p class="text-end">Age:</p>
        <p class="border-b col-span-3"><%= @age %></p>

        <p class="text-end">Address:</p>
        <p class="border-b col-span-3"><%= @affiliate.address %></p>

        <p class="text-end">Contact No:</p>
        <p class="border-b col-span-3"><%= @affiliate.mobile %></p>

        <p class="text-end">Identity Verification:</p>
        <div class="border-b col-span-3 flex gap-3 items-center">
            <p><%= @affiliate.type_of_id %></p>
            <% if @affiliate.attached_id.present? %>
                <%= image_tag @affiliate.attached_id, alt: 'src', class: "w-36 h-36" %>
            <% end %>
        </div>

        <p class="text-end">Email:</p>
        <p class="border-b col-span-3"><%= @affiliate.email %></p>

        <p class="text-end">Facebook:</p>
        <p class="border-b col-span-3"><%= @affiliate.fb %></p>

        <p class="text-end">Instagram:</p>
        <p class="border-b col-span-3"><%= @affiliate.ig %></p>

        <p class="text-end">Tiktok:</p>
        <p class="border-b col-span-3"><%= @affiliate.tiktok %></p>

        <p class="text-end">Youtube:</p>
        <p class="border-b col-span-3"><%= @affiliate.youtube %></p>

        <p class="text-end">Others:</p>
        <p class="border-b col-span-3"><%= @affiliate.others %></p>
    </div>

    <div class="text-end">
        <%= link_to admin_affiliates_path, class: 'inline-block bg-green-700 text-white px-6 py-2 rounded-full' do %>
            Back
        <% end %>
    </div>
</div>