config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :salespeople
    resources :buyers
    resources :sales
    resources :affiliates
  end
  
  devise_for :affiliates
  devise_for :admins, controllers: { sessions: 'admin/sessions'}

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  authenticated :affiliate_user do
    root to: "affiliate#index", as: :affiliate_root
  end

  # resources :affiliate

  get "admin" => "admin#index"
  get "admin/payment_history" => "admin#payment_history"
  get "affiliate" => "affiliate#index"
  get "affiliate/profile" => "affiliate#profile"
  get "affiliate/profile/edit" => "affiliate#edit"
  patch "affiliate/update" => "affiliate#update"
  get "affiliate/sale" => "affiliate#sale"
  get "affiliate/account" => "affiliate#account"
  get "affiliate/account_setting" => "affiliate#account_setting"
  get "affiliate/account_setting/edit/" => "affiliate#edit_account_setting"
  patch "affiliate/account_setting/update" => "affiliate#update_account_setting"

  get "sales/invest/form/:ref_code" => "sales#new", as: :sales_form
  post "sales/invest/form/create" => "sales#create"
  get "sales/invest/message" => "sales#message", as: :sales_message

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: redirect('affiliates/sign_in')
end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  has_one_attached :attached_id

  has_many :sales

  def ref_code
    return self.id.to_s.rjust(4, '0')
  end

  def payout
    return self.sales.any? ? self.sales.sum(:payout) : 0
  end

  def last_payment
    return self.sales.any? ? self.sales.last.updated_at.strftime("%B %d, %Y") : ''
  end
end

app/controllers/admin/affiliates_controller.rb
class Admin::AffiliatesController < AdminController
  def index
    respond_to do |format|
      format.html do
        @admin_affiliates = Affiliate.all.order(id: :asc)
      end
      format.xlsx do
        @admin_affiliates = Affiliate.all.order(id: :asc)
        render xlsx: 'admin/affiliates', template: 'admin/affiliates/template'
      end
    end
  end

  def new
    @admin_affiliate = Affiliate.new
  end

  def show
    @affiliate = Affiliate.find(params[:id])

    if @affiliate.birthday.present?
      now = Time.now.utc.to_date
      @age = now.year - @affiliate.birthday.to_date.year

      if (now.month < @affiliate.birthday.to_date.month)
        @age = @age - 1
      end
    end
  end

  def create
    @admin_affiliate = Affiliate.new(admin_affiliate_params)

    respond_to do |format|
      if @admin_affiliate.save
        format.html { redirect_to admin_affiliates_url(@admin_affiliate), notice: "Affiliate was successfully created." }
        format.json { render :show, status: :created, location: @admin_affilliate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_affilliate.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def admin_affiliate_params
    params.require(:affiliate).permit(:fullname, :email, :password, :password_confirmation, :address, :mobile)
  end
end

app/controllers/affiliate_controller.rb
class AffiliateController < ApplicationController
  layout 'affiliate'
  before_action :authenticate_affiliate!
  before_action :set_affiliate, only: %i[index profile edit update account_setting edit_account_setting update_account_setting]

  def index
    @pending = current_affiliate.sales.pending.count
    @paid = current_affiliate.sales.paid.count
  end

  def profile
    if @affiliate.birthday.present?
      now = Time.now.utc.to_date
      @age = now.year - @affiliate.birthday.to_date.year

      if (now.month < @affiliate.birthday.to_date.month)
        @age = @age - 1
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|

      if @affiliate.update(affiliate_params)
        format.html { redirect_to affiliate_profile_path, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @affiliate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @affiliate.errors, status: :unprocessable_entity }
      end
    end
  end

  def sale
    @sales = current_affiliate.sales
  end

  def account
  end

  def account_setting
  end

  def edit_account_setting
  end

  def update_account_setting
    respond_to do |format|

      if @affiliate.update(affiliate_params)
        format.html { redirect_to affiliate_account_setting_path, notice: "Account Settings was successfully updated." }
        format.json { render :show, status: :ok, location: @affiliate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @affiliate.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    def set_affiliate
      @affiliate = Affiliate.find(current_affiliate.id)
    end

    def affiliate_params
      params.require(:affiliate).permit(:birthday, :address, :mobile, :password, :password_confirmation, :fb, :ig, :tiktok, :youtube, :others, :type_of_id, :avatar, :attached_id, :bank, :account_name, :account_no)
    end
end

app/helpers/admin/affiliates_helper.rb
module Admin::AffiliatesHelper
end

app/views/affiliate/account.html.erb
<section class="px-10 py-10">
    <div class="flex justify-between text-2xl mb-20">
        <h1>My Account</h1>
    </div>
    <h2>Transaction History:</h2>
    <div class="flex bg-gray-300 p-2 my-2">
        <p class="flex-1">Transaction Type</p>
        <p class="flex-1">Amount</p>
        <p class="flex-1">Date</p>
    </div>


    <div class="flex bg-green-500 p-2 my-2">
        <p class="flex-1 flex gap-1 items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#fff" viewBox="0 0 256 256"><path d="M231.39,132.94A8,8,0,0,0,224,128H184V48a16,16,0,0,0-16-16H88A16,16,0,0,0,72,48v80H32a8,8,0,0,0-5.66,13.66l96,96a8,8,0,0,0,11.32,0l96-96A8,8,0,0,0,231.39,132.94ZM128,220.69,51.31,144H80a8,8,0,0,0,8-8V48h80v88a8,8,0,0,0,8,8h28.69Z"></path></svg>
            Payout
        </p>
        <p class="flex-1"><%= current_affiliate.payout %></p>
        <p class="flex-1"><%= current_affiliate.last_payment %></p>
    </div>

</section>

app/views/affiliate/account_setting.html.erb
<div class="mt-20 px-10 mx-auto w-8/12">
    <h1 class="text-2xl mb-20">Account Setting</h1>
    <div class="grid grid-cols-4 gap-2 text-lg">
        <p class="text-end">Bank: </p>
        <p class="border-b col-span-3"><%= @affiliate.bank %></p>

        <p class="text-end">Account Name: </p>
        <p class="border-b col-span-3"><%= @affiliate.account_name %></p>

        <p class="text-end">Account No.: </p>
        <p class="border-b col-span-3"><%= @affiliate.account_no %></p>
       
    </div>

    <div class="text-end mt-10">
        <%= link_to 'Edit', affiliate_account_setting_edit_path, class: 'py-2 px-6 bg-green-700 text-white rounded-full' %>
    </div>
</div>

app/views/affiliate/edit.html.erb
<%= form_with(model: @affiliate, url: "/affiliate/update") do |form| %>
  <div class="relative" data-controller="profile">
    <%= image_tag @affiliate.avatar.present? ? @affiliate.avatar : 'user.png', alt: 'src', class: "w-36 h-36 inline-block rounded-full thumbnail" %>
    <h1 class="inline-block text-3xl"><%= @affiliate.fullname %></h1>
    <%= form.file_field :avatar, class: 'btn-thumbnail absolute bottom-0 left-32 file:border-0 file:rounded-full file:bg-green-700 file:px-2 file:text-white' %>
  </div>
  <% if @affiliate.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@affiliate.errors.count, "error") %> prohibited this affiliate from being saved:</h2>

      <ul>
        <% @affiliate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid grid-cols-4 w-8/12 ml-28 gap-2 items-center mt-10">
    <%= form.label :birthday, class: 'text-end' %>
    <%= form.date_field :birthday, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <%= form.label :email, class: "text-end" %>
    <%= form.text_field :email, readonly: true, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <%= form.label :address, class: "text-end" %>
    <%= form.text_field :address, required: true, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <%= form.label :mobile, "Contact No.", class: "text-end" %>
    <%= form.text_field :mobile, required: true, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <%= form.label :type_of_id, "Identity Verification", class: "text-end" %>
    <div class="col-span-3 grid grid-cols-3 items-center gap-1">
      <%= form.select :type_of_id, ["Drivers License", "UMID", "Philhealth", "Philippine passport", "NBI", "Postal ID", "TIN ID", "SSS ID"], {}, :class => "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent" %>
      <%= form.file_field :attached_id, class: "file:border-0 file:rounded-full file:bg-green-700 file:px-2 file:text-white" %>
      <% if @affiliate.attached_id.present? %>
        <%= image_tag @affiliate.attached_id, alt: 'src', class: "w-36 h-36" %>
      <% end %>
    </div>

    <div class="text-end">
      <%= form.label :password, class: "text-end" %>
    </div>
    <div class="col-span-3">
      <%= form.password_field :password, required: true, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent w-full" %>
    </div>

    <div class="text-end">
      <%= form.label :password_confirmation, class: "text-end" %>
    </div>

    <div class="col-span-3">
      <%= form.password_field :password_confirmation, required: true, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent w-full" %>
    </div>


    <%= form.label :fb, "Facebook", class: "text-end" %>
    <%= form.text_field :fb, required: true, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <%= form.label :ig, "Instagram", class: "text-end" %>
    <%= form.text_field :ig, required: true, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>

    <%= form.label :tiktok, "Tiktok", class: "text-end" %>
    <%= form.text_field :tiktok, required: true, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <%= form.label :youtube, class: "text-end" %>
    <%= form.text_field :youtube, required: true, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <%= form.label :others, class: "text-end" %>
    <%= form.text_field :others, class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <div class="inline col-span-full mt-5 text-end">
      <%= form.submit "Update Details", class: "rounded-full py-3 px-5 bg-green-700 text-white inline-block font-medium cursor-pointer" %>
    </div>
  </div>
<% end %>

app/views/affiliate/edit_account_setting.html.erb
<%= form_with(model: @affiliate, url: "/affiliate/account_setting/update") do |form| %>
  <% if @affiliate.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@affiliate.errors.count, "error") %> prohibited this affiliate from being saved:</h2>

      <ul>
        <% @affiliate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1 class="text-2xl mb-20 w-8/12 mx-auto mt-10">Account Setting</h1>

  <div class="grid grid-cols-4 w-8/12 ml-28 gap-2 items-center mt-10">
    <%= form.label :bank, class: 'text-end' %>
    <%= form.text_field :bank, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <%= form.label :account_name, class: 'text-end' %>
    <%= form.text_field :account_name, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <%= form.label :account_no, class: 'text-end' %>
    <%= form.text_field :account_no, required: true,  class: "border-transparent border-b-gray-500 focus:border-transparent focus:border-b-gray-500 focus:ring-transparent col-span-3" %>
  
    <div class="inline col-span-full mt-5 text-end">
      <%= form.submit "Update Details", class: "rounded-full py-3 px-5 bg-green-700 text-white inline-block font-medium cursor-pointer" %>
    </div>
  </div>
<% end %>

app/views/affiliate/index.html.erb
<div class="flex justify-between items-end px-10 items-center">
    <div>
        <h1 class="font-medium text-xl uppercase">Affiliate Link</h1>
        
        <%= link_to sales_form_path(current_affiliate.ref_code), class: 'hover:text-green-700', target: :_blank do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="inline-block" width="32" height="32" fill="#000000" viewBox="0 0 256 256"><path d="M240,88.23a54.43,54.43,0,0,1-16,37L189.25,160a54.27,54.27,0,0,1-38.63,16h-.05A54.63,54.63,0,0,1,96,119.84a8,8,0,0,1,16,.45A38.62,38.62,0,0,0,150.58,160h0a38.39,38.39,0,0,0,27.31-11.31l34.75-34.75a38.63,38.63,0,0,0-54.63-54.63l-11,11A8,8,0,0,1,135.7,59l11-11A54.65,54.65,0,0,1,224,48,54.86,54.86,0,0,1,240,88.23ZM109,185.66l-11,11A38.41,38.41,0,0,1,70.6,208h0a38.63,38.63,0,0,1-27.29-65.94L78,107.31A38.63,38.63,0,0,1,144,135.71a8,8,0,0,0,16,.45A54.86,54.86,0,0,0,144,96a54.65,54.65,0,0,0-77.27,0L32,130.75A54.62,54.62,0,0,0,70.56,224h0a54.28,54.28,0,0,0,38.64-16l11-11A8,8,0,0,0,109,185.66Z"></path></svg>
            <p class="text-lg inline-block">https://<%= "#{request.host_with_port}/sales/invest/form/#{current_affiliate.ref_code}" %></p>
        <% end %>
    </div>

    <div class="text-end">
        <h1 class="font-medium text-xl uppercase">Referral Code</h1>
        <p class="text-2xl"><%= current_affiliate.ref_code %></p>
    </div>
</div>

<div class="flex gap-5 mt-10 justify-center">
    <div class="bg-green-500 min-w-40 text-center py-4 px-12 rounded-lg">
        <p class="uppercase">Closed Sales</p>
        <p class="font-bold text-5xl"><%= @paid %></p>
    </div>
    <div class="bg-yellow-500 min-w-40 text-center py-4 px-12 rounded-lg">
        <p class="uppercase">pending</p>
        <p class="font-bold text-5xl"><%= @pending %></p>
    </div>
</div>

app/views/affiliate/profile.html.erb
<div class="px-5">
    <%= image_tag @affiliate.avatar.present? ? @affiliate.avatar : 'user.png', alt: 'src', class: "w-36 h-36 inline-block rounded-full" %>
    <h1 class="inline-block text-3xl"><%= @affiliate.fullname %></h1>

    <div class="grid grid-cols-4 w-8/12 ml-28 gap-2">
        <p class="text-end">Referral Code:</p>
        <p class="border-b col-span-3"><%= @affiliate.id.to_s.rjust(4, '0') %></p>
        
        <p class="text-end">Birthday:</p>
        <p class="border-b col-span-3"><%= @affiliate.birthday.present? ? @affiliate.birthday.strftime("%B %d, %Y") : '' %></p>

        <p class="text-end">Age:</p>
        <p class="border-b col-span-3"><%= @age %></p>

        <p class="text-end">Address:</p>
        <p class="border-b col-span-3"><%= @affiliate.address %></p>

        <p class="text-end">Contact No:</p>
        <p class="border-b col-span-3"><%= @affiliate.mobile %></p>

        <p class="text-end">Email:</p>
        <p class="border-b col-span-3"><%= @affiliate.email %></p>

        <p class="text-end">Facebook:</p>
        <p class="border-b col-span-3"><%= @affiliate.fb %></p>

        <p class="text-end">Instagram:</p>
        <p class="border-b col-span-3"><%= @affiliate.ig %></p>

        <p class="text-end">Tiktok:</p>
        <p class="border-b col-span-3"><%= @affiliate.tiktok %></p>

        <p class="text-end">Youtube:</p>
        <p class="border-b col-span-3"><%= @affiliate.youtube %></p>

        <p class="text-end">Others:</p>
        <p class="border-b col-span-3"><%= @affiliate.others %></p>
    </div>

    <div class="text-end">
        <%= link_to affiliate_profile_edit_path, class: 'inline-block bg-green-700 text-white px-6 py-2 rounded-full' do %>
            Edit
        <% end %>
    </div>
</div>

app/views/affiliate/sale.html.erb
<h1 class="text-2xl text-green-800 text-center uppercase font-medium mt-12 uppercase">Sales</h1>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-12">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400 overflow-x-scroll max-w-full">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Client Name
                </th>
                <th scope="col" class="px-6 py-3">
                    Referral Code
                </th>
                <th scope="col" class="px-6 py-3">
                    Transaction Date
                </th>
                <th scope="col" class="px-6 py-3">
                    Payment Method
                </th>
                <th scope="col" class="px-6 py-3">
                    Purchase Share
                </th>
                <th scope="col" class="px-6 py-3">
                    Amount
                </th>
                <th scope="col" class="px-6 py-3">
                    Total
                </th>
                <th scope="col" class="px-6 py-3">
                    Payout
                </th>
                <th scope="col" class="px-6 py-3">
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            <% @sales.each do |sale| %>
                <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        <%= sale.buyer_name %>
                    </th>
                    <td class="px-6 py-4">
                        <%= sale.ref_code %>
                    </td>
                    <td class="px-6 py-4">
                        <%= sale.transaction_date.present? ? sale.transaction_date.strftime("%B %d, %Y") : '' %>
                    </td>
                    <td class="px-6 py-4">
                        <%= sale.payment_method %>
                    </td>
                    <td class="px-6 py-4">
                        <%= sale.purchase_share %>
                    </td>
                    <td class="px-6 py-4">
                        <%= sale.amount %>
                    </td>
                    <td class="px-6 py-4">
                        <%= sale.total_amount %>
                    </td>
                    <td class="px-6 py-4">
                        <%= sale.payout %>
                    </td>
                    <td class="px-6 py-4 capitalize">
                        <%= sale.status %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
