config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :salespeople
    resources :buyers
    resources :sales
    resources :affiliates
  end
  
  devise_for :affiliates
  devise_for :admins, controllers: { sessions: 'admin/sessions'}

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  authenticated :affiliate_user do
    root to: "affiliate#index", as: :affiliate_root
  end

  # resources :affiliate

  get "admin" => "admin#index"
  get "admin/payment_history" => "admin#payment_history"
  get "affiliate" => "affiliate#index"
  get "affiliate/profile" => "affiliate#profile"
  get "affiliate/profile/edit" => "affiliate#edit"
  patch "affiliate/update" => "affiliate#update"
  get "affiliate/sale" => "affiliate#sale"
  get "affiliate/account" => "affiliate#account"
  get "affiliate/account_setting" => "affiliate#account_setting"
  get "affiliate/account_setting/edit/" => "affiliate#edit_account_setting"
  patch "affiliate/account_setting/update" => "affiliate#update_account_setting"

  get "sales/invest/form/:ref_code" => "sales#new", as: :sales_form
  post "sales/invest/form/create" => "sales#create"
  get "sales/invest/message" => "sales#message", as: :sales_message

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: redirect('affiliates/sign_in')
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrioDeAgohoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="flex min-h-screen">
        <nav class="sidebar w-64 min-w-64 bg-green-800 text-white text-center uppercase font-medium">
            <ul>
                <li class="py-4 border-b text-xl text-orange-400 <%= request.fullpath.length == 6 ? 'bg-white' : '' %>">
                    <%= link_to admin_path, class: 'link' do %>
                        Admin Dashboard
                    <% end %>
                </li>
                <li class="py-4 border-b <%= request.fullpath.include?('sales') && request.fullpath.length == 12 ? 'bg-white text-green-800' : '' %>">
                    <%= link_to admin_sales_path, class: 'link' do %>
                        Sales Summary & Payment Transactions
                    <% end %>
                </li>
                <li class="py-4 border-b <%= request.fullpath.include?('affiliates') ? 'bg-white text-green-800' : '' %>">
                    <%= link_to admin_affiliates_path, class: 'link' do %>
                        Affiliate Database
                    <% end %>
                </li>
                <li class="py-4 border-b <%= request.fullpath.include?('buyers') ? 'bg-white text-green-800' : '' %>">
                    <%= link_to admin_buyers_path, class: 'link' do %>
                        Buyers Database
                    <% end %>
                </li>
                <li class="py-4 border-b <%= request.fullpath.include?('payment_history') ? 'bg-white text-green-800' : '' %>">
                    <%= link_to admin_payment_history_path, class: 'link' do %>
                        Payment History
                    <% end %>
                </li>
                <li class="py-4 border-b <%= request.fullpath.include?('salespeople') ? 'bg-white text-green-800' : '' %>">
                    <%= link_to admin_salespeople_path, class: 'link' do %>
                        Salesperson
                    <% end %>
                </li>
                <li class="py-4 border-b">
                    <% if admin_signed_in? %>
                        <%= link_to "Sign out", destroy_admin_session_path, data: { 'turbo-method' => :delete, 'turbo_confirm' => "Are you sure?"  } %>
                    <% end %>
                </li>
            </ul>
        </nav>
        <main class="flex-1 m-8 w-full overflow-x-scroll">
            <%= yield %>
        </main>
    </div>
  </body>
</html>

app/views/layouts/admin_session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrioDeAgohoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen grid grid-cols-3 justify-center items-center bg-green-800 text-white bg-cover" style="background-image:linear-gradient(rgba(36,74,32, 0.95), rgba(36,74,32, 0.95)), url(/assets/brio-de-agoho-bg.jpg)">
    <main class="col-start-2">
      <%= yield %>
    </main>
    <section class="self-start text-center mt-8">
        <svg xmlns="http://www.w3.org/2000/svg" class="mx-auto" width="64" height="64" fill="#ffffff" viewBox="0 0 256 256"><path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24ZM74.08,197.5a64,64,0,0,1,107.84,0,87.83,87.83,0,0,1-107.84,0ZM96,120a32,32,0,1,1,32,32A32,32,0,0,1,96,120Zm97.76,66.41a79.66,79.66,0,0,0-36.06-28.75,48,48,0,1,0-59.4,0,79.66,79.66,0,0,0-36.06,28.75,88,88,0,1,1,131.52,0Z"></path></svg>
        <p class="text-lg uppercase font-medium">Admin Log-in</p>
    </section>
  </body>
</html>

app/views/layouts/affiliate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrioDeAgohoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex min-h-screen" data-controller="navigation">
        <nav class="sidebar w-full fixed md:static z-10 md:w-64 min-w-64 bg-green-800 text-white text-center uppercase font-medium md:block">
            <div class="flex">
                <svg xmlns="http://www.w3.org/2000/svg" class="p-2 menu-btn md:hidden" width="50" height="50" fill="#fff" viewBox="0 0 256 256"><path d="M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128ZM40,72H216a8,8,0,0,0,0-16H40a8,8,0,0,0,0,16ZM216,184H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Z"></path></svg>
                
                <svg xmlns="http://www.w3.org/2000/svg" class="p-2 hidden close-btn md:hidden" width="50" height="50" fill="#fff" viewBox="0 0 256 256"><path d="M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"></path></svg>
            </div>

            <ul class="hidden md:block">
                <li class="py-4 border-b text-xl text-orange-400 <%= request.fullpath.length == 10 ? 'bg-white' : '' %>">
                    <%= link_to affiliate_path, class: 'link' do %>
                        Dashboard
                    <% end %>
                </li>
                <li class="py-4 border-b <%= request.fullpath.include?('profile') ? 'bg-white text-green-800' : '' %>">
                    <%= link_to affiliate_profile_path, class: 'link' do %>
                        Profile
                    <% end %>
                </li>
                <li class="py-4 border-b <%= request.fullpath.include?('sale') ? 'bg-white text-green-800' : '' %>">
                    <%= link_to affiliate_sale_path, class: 'link' do %>
                        Sales
                    <% end %>
                </li>
                <li class="py-4 border-b <%= request.fullpath.split('/')[-1] == 'account' ? 'bg-white text-green-800' : '' %>">
                    <%= link_to affiliate_account_path, class: 'link' do %>
                        My Account
                    <% end %>
                </li>
                <li class="py-4 border-b <%= request.fullpath.include?('account_setting') ? 'bg-white text-green-800' : '' %>">
                    <%= link_to affiliate_account_setting_path, class: 'link' do %>
                        Account Setting
                    <% end %>
                </li>
                <li class="py-4 border-b">
                    <% if affiliate_signed_in? %>
                        <%= link_to "Sign out", destroy_affiliate_session_path, data: { 'turbo-method' => :delete, 'turbo_confirm' => "Are you sure?"  } %>
                    <% end %>
                </li>
            </ul>
        </nav>
        <main class="flex-1 m-4 w-full overflow-hidden mt-20 md:mt-4">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>
        </main>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrioDeAgohoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen grid grid-cols-3 justify-center items-center bg-[url('brio-de-agoho-bg-transparent.jpg')] bg-cover">
    <main class="col-start-2">
      <%= yield %>
    </main>
    <section class="self-start text-center mt-8">
        <svg xmlns="http://www.w3.org/2000/svg" class="mx-auto" width="64" height="64" fill="#000" viewBox="0 0 256 256"><path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24ZM74.08,197.5a64,64,0,0,1,107.84,0,87.83,87.83,0,0,1-107.84,0ZM96,120a32,32,0,1,1,32,32A32,32,0,0,1,96,120Zm97.76,66.41a79.66,79.66,0,0,0-36.06-28.75,48,48,0,1,0-59.4,0,79.66,79.66,0,0,0-36.06,28.75,88,88,0,1,1,131.52,0Z"></path></svg>
        <p class="text-lg uppercase font-medium">Affiliate Log-in</p>
    </section>
  </body>
</html>

app/views/layouts/sales.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrioDeAgohoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen md:grid md:grid-cols-4 justify-center items-center bg-[url('beach.jpg')] bg-cover">
    <main class="md:col-start-2 md:col-span-2">
      <%= yield %>
    </main>
  </body>
</html>